version: '2'
services:
  master:
    container_name: habitat_master
    extends:
      file: .base.yml
      service: base
  slave:
    extends:
      file: .base.yml
      service: base
    volumes:
      - /hab/sup
      - /hab/svc
    volumes_from:
      - master
