version: '2'
services:
  habitat:
    container_name: habitat
    build:
      context: .
      args:
        uid: ${UID}
    image: habitat
    volumes:
      - .:/mnt
    stdin_open: true
    tty: true
    command: /bin/sh
    cap_add:
      - SYS_ADMIN
